---

- name: "Create client {{ item.name }} policies (enabled: yes)"
  template:
    src: "{{ bacula_policies_template_folder }}/{{ policy.name }}.conf.j2"
    dest: "/etc/bacula/policies.d/{{ item.name }}-{{ policy.name }}.conf"
    owner: bacula
    group: tape
    mode: 0640
  notify:
    - Bacula-director restarted
  no_log: "{{ bacula_no_log|bool }}"
