---

- name: Install dependencies to compile telegram-cli
  apt:
    name: "{{ item }}"
    update_cache: true
  loop:
  - git
  - libreadline-dev
  - libconfig-dev
  - libssl-dev
  - zlib1g-dev
  - libgcrypt20-dev
  - lua5.2
  - liblua5.2-dev
  - libevent-dev
  - libjansson-dev
  - libpython-dev
  - make

- name: Clone telegram-cli
  git:
    repo: https://github.com/vysheng/tg.git
    dest: /usr/local/src/telegram-cli
    recursive: true
  when:
  - bacula_messages_telegram_install|bool

- name: Run configure
  command:
    cmd: ./configure --disable-openssl
    chdir: /usr/local/src/telegram-cli
  environment:
    CFLAGS: "-Wno-cast-function-type"

- name: Run make 'install'
  make:
    chdir: /usr/local/src/telegram-cli
    params:
      NUM_THREADS: 8

- name: Create directories
  file:
    name: "{{ item }}"
    state: directory
  loop:
    - /usr/local/telegram-cli
    - /usr/local/telegram-cli/keys
    - /usr/local/telegram-cli/profiles
    - /usr/local/telegram-cli/log
    - /etc/bacula/scripts/

- name: Move telegram-cli to bin
  copy:
    src: /usr/local/src/telegram-cli/bin/telegram-cli
    dest: /usr/local/bin/telegram-cli
    remote_src: true

- name: Move keys
  copy:
    src: /usr/local/src/telegram-cli/server.pub
    dest: /usr/local/telegram-cli/keys/server.pub
    remote_src: true

- name: Move keys
  copy:
    src: /usr/local/src/telegram-cli/tg-server.pub
    dest: /usr/local/telegram-cli/keys/tg-server.pub
    remote_src: true

- name: Create default configuration
  copy:
    content: | 
      default_profile = "bacula";
      bacula = {
          config_directory = "/usr/local/telegram-cli/profiles/bacula";
          msg_num = true;
          binlog_enabled = true;
          log_level = 2;
      }; 
    dest: /etc/telegram.conf
  when:
    - bacula_messages_telegram_install|bool
    - bacula_messages_telegram_create_config|bool   

- name: Create script for telegram messages
  template:
    mode: u=rx,g=rx
    src: telegram_script.sh.j2
    dest: /etc/bacula/scripts/_send_telegram.sh 
